# Generated by Django 4.1.7 on 2023-04-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pharmacy_images'),
        ),
    ]
