# Generated by Django 4.1.7 on 2023-06-08 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile_shop_site', '0003_rename_reapir_name_repaircost_repair_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, to='mobile_shop_site.mobile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobileShop_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
